### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by alekna** [h2non/riprova#21]
Few deprecation warnings. FYI.

```python
/usr/local/lib/python3.8/site-packages/riprova/async_retrier.py:141: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
self.on_retry = asyncio.coroutine(on_retry) if on_retry else None
```

```python
/usr/local/lib/python3.8/site-packages/riprova/async_retrier.py:279: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
return (yield from asyncio.wait_for(
```

**Comment by bleetube** [comment]
My distro just updated to Python 3.11 and now a downstream script depending on this no longer works:

```python
Traceback (most recent call last):
  File "/opt/bitcoind_exporter/bitcoin-prometheus-exporter/bitcoind-monitor.py", line 33, in <module>
    import riprova
  File "/opt/bitcoind_exporter/.local/lib/python3.11/site-packages/riprova/__init__.py", line 2, in <module>
    from .retry import retry
  File "/opt/bitcoind_exporter/.local/lib/python3.11/site-packages/riprova/retry.py", line 8, in <module>
    from .async_retrier import AsyncRetrier
  File "/opt/bitcoind_exporter/.local/lib/python3.11/site-packages/riprova/async_retrier.py", line 17, in <module>
    class AsyncRetrier(Retrier):
  File "/opt/bitcoind_exporter/.local/lib/python3.11/site-packages/riprova/async_retrier.py", line 151, in AsyncRetrier
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```
Luckily the script I use provides a docker container, so I can start using that as a workaround for now.  I run Arch, btw

**Comment by EchterAgo** [comment]
So, this has already been fixed in the github release / master branch, but the version of the package on pypi is still 0.2.7, the latest github tab is 0.3.1. when i install 0.3.1 from github everything works with python 3.11. is 0.3.1 intentionally not on pypi?

**Comment by EchterAgo** [comment]
This was fixed by #23
